// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJsZ6p0iAAxnfivqU7LgF_49c9MpQ_y_8',
    appId: '1:288839383676:web:aaf8240662a0f0c6e967f9',
    messagingSenderId: '288839383676',
    projectId: 'tiny-human',
    authDomain: 'tiny-human.firebaseapp.com',
    storageBucket: 'tiny-human.appspot.com',
    measurementId: 'G-NMC3NJX1HS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCIbt-YvqC9iZA8CPueUmNZ57Oe-8WKTEI',
    appId: '1:288839383676:android:01195cba0bebdb30e967f9',
    messagingSenderId: '288839383676',
    projectId: 'tiny-human',
    storageBucket: 'tiny-human.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBrnanQBJywue91Lpj-M9uSSq-TfcPhph8',
    appId: '1:288839383676:ios:9ea169e1a559d6f6e967f9',
    messagingSenderId: '288839383676',
    projectId: 'tiny-human',
    storageBucket: 'tiny-human.appspot.com',
    iosBundleId: 'com.example.tinyHumanApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBrnanQBJywue91Lpj-M9uSSq-TfcPhph8',
    appId: '1:288839383676:ios:e2c1c4b626fbddf3e967f9',
    messagingSenderId: '288839383676',
    projectId: 'tiny-human',
    storageBucket: 'tiny-human.appspot.com',
    iosBundleId: 'com.example.tinyHumanApp.RunnerTests',
  );
}
